development:
  adapter: postgresql
  encoding: unicode
  database: sna_development
  pool: 5
  username: ouyang
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sna_test
  pool: 5
  username: ouyang
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sna_production
  pool: 5
  username: ouyang
  password:


cucumber:
  <<: *test